# Generated by Django 3.2.12 on 2022-10-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
