# Generated by Django 3.2.12 on 2022-10-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(blank=True, choices=[('unpaid', 'UnPayed'), ('payed', 'Payed')], default='unpaid', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('pending', 'Pending'), ('dismissed', 'Dismissed')], default='pending', max_length=10, null=True)),
                ('sections', models.ManyToManyField(to='academy.Section')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'ordering': ['-admission_date'],
            },
        ),
    ]
