# Generated by Django 3.2.12 on 2022-10-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-admission_date'], 'permissions': [('create_student_tree', 'Can create the students with status is applied'), ('close_task', 'Can remove a task by setting its status as closed')], 'verbose_name': 'student'},
        ),
    ]
