# Generated by Django 3.2.12 on 2022-10-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-admission_date'], 'verbose_name': 'student'},
        ),
    ]
