# Generated by Django 3.2.12 on 2022-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_branch_location'),
        ('students', '0006_alter_student_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(blank=True, to='academy.Section'),
        ),
    ]
