# Generated by Django 3.2.12 on 2022-10-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
    ]
