# Generated by Django 3.2.12 on 2022-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_result_number_of_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
