# Generated by Django 3.2.12 on 2022-10-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='role',
            field=models.CharField(choices=[('profile_image', 'Profile Image'), ('cover_image', 'Cover Image'), ('gallery_image', 'Gallery Image')], default='gallery_image', max_length=15),
        ),
    ]
