# Generated by Django 3.2.12 on 2022-10-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters.', max_length=191, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
