# Generated by Django 3.2.12 on 2022-10-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('create_student_tree', 'Student Registerer'), ('create_academy_tree', 'Student Registerer')], 'verbose_name': 'user'},
        ),
    ]
