# Generated by Django 3.2.12 on 2022-10-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_create_branch', 'can create branch'), ('can_update_branch', 'can update branch'), ('can_delete_branch', 'can delete branch'), ('can_create_department', 'can create department'), ('can_update_department', 'can update department'), ('can_delete_department', 'can delete department'), ('can_create_subject', 'can create subject'), ('can_update_subject', 'can update subject'), ('can_delete_subject', 'can delete subject'), ('can_create_section', 'can create section'), ('can_update_section', 'can update section'), ('can_delete_section', 'can delete section'), ('can_register_user_and_student', 'can register user and student'), ('can_create_student', 'can create student'), ('can_update_student', 'can update student'), ('can_delete_student', 'can delete student')], 'verbose_name': 'user'},
        ),
    ]
