# Generated by Django 3.2.12 on 2022-10-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('scheduled', 'Scheduled'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=20, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('comments', models.ManyToManyField(blank=True, to='home.Comment')),
                ('files', models.ManyToManyField(blank=True, to='main.File')),
                ('images', models.ManyToManyField(blank=True, to='main.Image')),
                ('reviews', models.ManyToManyField(blank=True, to='home.Review')),
            ],
            options={
                'verbose_name': 'blog',
                'ordering': ['-published', '-updated', '-created'],
            },
        ),
    ]
