# Generated by Django 3.2.12 on 2022-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
