# Generated by Django 3.2.12 on 2022-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_view'),
        ('blog', '0007_auto_20221012_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, to='home.View'),
        ),
    ]
