# Generated by Django 3.2.12 on 2022-10-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20221018_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_from', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to', to='blog.comment'),
        ),
    ]
