# Generated by Django 3.2.12 on 2022-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pin_to_top',
            field=models.BooleanField(default=False),
        ),
    ]
