# Generated by Django 3.2.12 on 2022-10-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('educational_background', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=250, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('reviews', models.ManyToManyField(blank=True, to='home.Review')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'ordering': ['-joining_date'],
            },
        ),
    ]
