# Generated by Django 3.2.12 on 2022-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221026_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='favicon',
            field=models.ImageField(help_text='Upload your website favicon - Standard for most desktop browsers. 32×32', upload_to='main/images'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='logo',
            field=models.ImageField(help_text='Upload your website logo - 120 x 40 ', upload_to='main/images'),
        ),
    ]
