# Generated by Django 3.2.12 on 2022-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_phonenumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='core_values',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='global_reach',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='teams',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='descriptions',
            field=models.TextField(blank=True, help_text='brief description of the organization, or a combination of the two. (this field can be markdown or HTML)', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='descriptions',
            field=models.TextField(blank=True, help_text='brief description of the team,(this field can be markdown or HTML)', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CoreValues',
        ),
    ]
