# Generated by Django 3.2.12 on 2022-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221027_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='descriptions',
            field=models.TextField(blank=True, help_text='(this field can be markdown or HTML)', null=True),
        ),
    ]
