# Generated by Django 3.2.12 on 2022-10-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'branch',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shift_time', models.TimeField()),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'section',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=12)),
                ('bio', models.TextField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('cover_image', models.ManyToManyField(blank=True, to='main.Image')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.department')),
            ],
            options={
                'verbose_name': 'subject',
                'ordering': ['name'],
            },
        ),
    ]
