# Generated by Django 3.2.12 on 2022-10-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('home', '0001_initial'),
        ('main', '0001_initial'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='home.Review'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='cover_image',
            field=models.ManyToManyField(blank=True, to='main.Image'),
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='home.Review'),
        ),
        migrations.AddField(
            model_name='section',
            name='subjects',
            field=models.ManyToManyField(to='academy.Subject'),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='cover_image',
            field=models.ManyToManyField(blank=True, to='main.Image'),
        ),
        migrations.AddField(
            model_name='department',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='home.Review'),
        ),
        migrations.AddField(
            model_name='branch',
            name='cover_image',
            field=models.ManyToManyField(blank=True, to='main.Image'),
        ),
        migrations.AddField(
            model_name='branch',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='home.Review'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'name', 'shift_time')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name',)},
        ),
    ]
