# Generated by Django 3.2.12 on 2022-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20221018_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.png', null=True, upload_to='accdemy/cover_image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.png', null=True, upload_to='accdemy/cover_image'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.png', null=True, upload_to='accdemy/cover_image'),
        ),
    ]
