# Generated by Django 3.2.12 on 2022-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20221018_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.jpg', null=True, upload_to='academy/cover_image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.jpg', null=True, upload_to='academy/cover_image'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cover_image',
            field=models.ImageField(blank=True, default='academy/cover_image.jpg', null=True, upload_to='academy/cover_image'),
        ),
    ]
