# Generated by Django 3.2.12 on 2022-10-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20221018_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created', 'name'], 'verbose_name': 'department'},
        ),
    ]
