# Generated by Django 3.2.12 on 2022-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
