# Generated by Django 3.2.12 on 2022-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='beginner', max_length=12),
            preserve_default=False,
        ),
    ]
