# Generated by Django 3.2.12 on 2022-10-26 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_section_it_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='it_is_full',
        ),
        migrations.AddField(
            model_name='section',
            name='maximum_number_of_students',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
