# Generated by Django 3.2.12 on 2022-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20221026_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
