# Generated by Django 3.2.12 on 2022-10-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20221027_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
