# Generated by Django 3.2.12 on 2022-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_branch_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='building',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='street',
        ),
    ]
